---
- name: Set /etc/localtime to {{ timezone }}
  copy: src=/usr/share/zoneinfo/{{ timezone }}
        dest=/etc/localtime
        owner=root
        group=root
        mode=0644
  when: ansible_os_family == "Debian"
  tags: [timezone]

- name: Set /etc/timezone to {{ timezone }}
  template: dest=/etc/timezone src=timezone.j2
  when: ansible_os_family == "Debian"
  tags: [timezone]

- name: Update tzdata
  shell: dpkg-reconfigure --frontend noninteractive tzdata
  tags: [timezone]

- name: Restart ntp
  service: name=ntp state=restarted enabled=yes
  tags: [timezone]